---
name: Checks

on: [push]


jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create .env file
        shell: bash
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          touch my_settings.py
          echo SECRET_KEY="$SECRET_KEY" >> my_settings.py
          cat my_settings.py
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
